### PR TITLE
Python3 only

### PR DESCRIPTION
**Pull request by SamuelDeleglise**
Uses coroutine to replace the low-level futures/callbacks previously used for asynchronous acquisition. Pro: improved code readbility/Cons: incompatible with python<3.5.

There might be some places where callbacks are still there (for instance the LoopModule still exists and is implemented in the old fashion, or the PyrplWidget status_bar which changes color after some time was not touched).

Lockbox still needs more unittests and probably an API refresh (see https://github.com/lneuhaus/pyrpl/issues/349#issuecomment-445477673)

### CODE REVIEW

**Comment by lneuhaus** [comment]
Just merged "develop-0.9.3" into master. To do before merging this branch:

- merge master into this branch and fix conflicts
- bump version from 0.9.5 to 1.0.0
- add list of changes to changelog.md
- pass tests on Python 3.7 and 3.8 (Python 3.6 and 3.9 are optional I guess)

**Comment by lneuhaus** [comment]
pinging @SamuelDeleglise again - otherwise I might go ahead and clean this up for merging.

**Comment by lneuhaus** [comment]
Hi @SamuelDeleglise , if you want let's try to merge this branch into master. Am I fine to click "update branch" here?

**Comment by lneuhaus** [comment]
Also noting that we should ideally remove all the `loop=LOOP` constructs from `async_utils.py`, since they are deprecated and break this version on Python>=3.10.

**Comment by SamuelDeleglise** [comment]
In principle, you can click to merge:  we are all using it in the lab. However, I am not 100 % sure what's the status of the unit-tests on this branch ...

Just to keep you updated, there are a few things coming up regarding pyrpl: you should get a pretty final version of the paper very soon,

**Comment by lneuhaus** [comment]
Sorry for my late reply, missed your message. I tried this yesterday and found this version to work better than `master`, so am happy to merge. For that same reason, I think it's better to merge this rather sooner and fix the tests later (`master` is more broken than this).

I tried to make you an admin but seems like that doesn't work with free github accounts? What's Tristan's username? I sent you an email so you have mine.

Thanks for taking time to write the paper.

**Comment by lneuhaus** [comment]
I kept this branch, but I suggest we keep it around in case anyone is so used to it after so many years. In that sense, it would also be fine to continue working on it, and opening a new PR with the next changes from it.

**Pull request merged**
