### PR TITLE
Switch to MIT license

### PR DESCRIPTION
**Pull request by lneuhaus**
We repeatedly get requests from industry about licensing PyRPL under a more industry-friendly license. People from industry claim that they are worried about the following scenario: 

1. Shipping a product that uses PyRPL as a library, baked into a larger application. 
2. The customer asking to reveal the source code as it is possible under GPLv3. 
3. The company would of course only send the source code for packages/libraries such as PyRPL that are licensed under GPLv3, not the rest.
4. A lawsuit taking place about the question whether PyRPL and other GPLv3 libraries having "infected" the remaining components of the software, and thereby requiring to open source everything.

I believe above is not a real issue, rather an unreasonable panic. At the same time, I understand that in industry nobody wants to entertain even the possibility of a lawsuit if it can be avoided, as even winning it would likely leave every party at a disadvantage due to the time and resources spent on it.  

As far as I can tell, companies are happy to contribute bugfixes to PyRPL, so the "sharing of PyRPL modifications" aspect of GPLv3 is not a major problem when switching to another license.

I suggest to discuss whether every co-author is happy with the switch to an MIT license. If not, maybe there is another license that we could agree on. In absence of negative feedback I will merge this PR in 2 weeks, i.e. on May 23, 2022.

### CODE REVIEW

**Comment by lneuhaus** [comment]
The only relevant lawsuit I coud find on the internet: https://en.wikipedia.org/wiki/Free_Software_Foundation,_Inc._v._Cisco_Systems,_Inc.

**Comment by SamuelDeleglise** [comment]
I am fine with switching to MIT license

**Comment by jneer** [comment]
I don't think my opinion really matters here, but I don't see a problem with switching to MIT.

**Comment by Jerome-LMA** [comment]
Nice to hear the interest from the industry! yes, please update the license according to what seems the most suitable.

**Pull request merged**
