### PR TITLE
Added script for Vivado project generation

### PR DESCRIPTION
**Pull request by ivan-galinskiy**
Here I have added a script from the official 0.94 version of RedPitaya that allows one to recreate the Vivado project, also including the custom PyRPL code.

### CODE REVIEW

**Comment by lneuhaus** [comment]
Cool, thanks a lot! There is already someone else who asked for this feature yesterday! I will merge it once I have the travis unit test running again.

**Comment by ivan-galinskiy** [comment]
Great, I'm glad it was helpful!

**Comment by ivan-galinskiy** [comment]
Hi again, Leonhard! Was it possible for you to merge the project generation file? I just stumbled across it again, and remembered this pull request =)

**Comment by lneuhaus** [comment]
merged into develop-0.9.3

**Pull request closed without merging**
